server:
    port: 8082

spring:
    application:
        name: crud
    datasource:
        driver-class-name: org.postgresql.Driver
        password: postgres
        url: jdbc:postgresql://localhost:5432/postgres
        username: postgres
    jpa:
        database: postgresql
        show-sql: false
        hibernate:
            ddl-auto: update
